"""End-to-end demo against a running server: ingest the two task files through the Upload
API, wait for asynchronous processing, run semantic queries against each file, exercise
metadata filters and delete, and write a Markdown transcript to docs/demo_output.md.

    python scripts/demo.py [--base-url http://localhost:8000] [--api-key KEY] [--answer]
"""

import argparse
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
SAMPLES = [
    (ROOT / "samples" / "Knowledge_Base_Sample.pdf", "ai,orchestration,whitepaper", {"source": "zapier", "team": "research"}),
    (ROOT / "samples" / "Source_Code_Sample.py", "proxy,scraping", {"team": "platform", "repo": "badger"}),
]

QUERIES = [
    # --- document RAG (Knowledge_Base_Sample.pdf) ---
    {"query": "What is AI orchestration?", "top_k": 3},
    {"query": "How is AI orchestration different from traditional iPaaS integration platforms?", "top_k": 3},
    {"query": "What is MCP (Model Context Protocol) and why does it matter?", "top_k": 3},
    {"query": "What productivity lift did the McKinsey report find for AI agents?", "top_k": 3},
    {"query": "How did Remote scale its IT helpdesk with a three-person team?", "top_k": 3},
    {"query": "What are the stages of the AI orchestration maturity model?", "top_k": 3},
    # --- code RAG (Source_Code_Sample.py) ---
    {"query": "How does a proxy's score recover over time after being used?", "top_k": 3},
    {"query": "What happens when a proxy request fails?", "top_k": 3},
    {"query": "How are user agents rotated and what happens when a UA gets blocked by a CAPTCHA?", "top_k": 3},
    {"query": "Where is the proxy list loaded from in the test script?", "top_k": 3},
    # --- metadata filtering ---
    {"query": "penalty factor and failure handling", "top_k": 3, "filters": {"file_types": ["pdf"]}},
    {"query": "penalty factor and failure handling", "top_k": 3, "filters": {"languages": ["python"], "tags": ["proxy"]}},
    {"query": "governance and risk guardrails", "top_k": 2, "filters": {"metadata": {"team": "research"}}},
]


class Transcript:
    def __init__(self):
        self.lines: list[str] = []

    def add(self, text: str = "") -> None:
        print(text)
        self.lines.append(text)

    def code(self, obj, lang: str = "json") -> None:
        body = obj if isinstance(obj, str) else json.dumps(obj, indent=2, ensure_ascii=False)
        self.add(f"```{lang}\n{body}\n```")


def snippet(text: str, n: int = 260) -> str:
    text = " ".join(text.split())
    return text if len(text) <= n else text[:n] + " ..."


STOP = {"what", "does", "how", "the", "and", "for", "with", "when", "where", "which", "from", "that", "this", "after", "being"}


def best_passage(text: str, query: str, n: int = 420) -> str:
    """The sentence(s) of a chunk that best match the query, so the transcript shows the
    evidence instead of the first N characters of the chunk."""
    terms = {t for t in re.findall(r"[a-z0-9]+", query.lower()) if len(t) > 2 and t not in STOP}
    flat = " ".join(text.split())
    sentences = re.split(r"(?<=[.!?])\s+", flat)
    if len(sentences) <= 1:
        return snippet(flat, n)
    scores = [sum(t in s.lower() for t in terms) for s in sentences]
    i = max(range(len(sentences)), key=lambda k: scores[k])
    out = sentences[i]
    j = i + 1
    while j < len(sentences) and len(out) + len(sentences[j]) < n:
        out += " " + sentences[j]
        j += 1
    return ("... " if i > 0 else "") + snippet(out, n)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default="http://localhost:8000")
    ap.add_argument("--api-key", default=None)
    ap.add_argument("--answer", action="store_true", help="also generate LLM answers via the AI gateway")
    ap.add_argument("--out", default=str(ROOT / "docs" / "demo_output.md"))
    args = ap.parse_args()

    headers = {"X-API-Key": args.api_key} if args.api_key else {}
    client = httpx.Client(base_url=args.base_url, headers=headers, timeout=120)
    t = Transcript()
    t.add("# Proof of execution: ingestion and querying of the two task files")
    t.add()
    t.add(f"Generated by `scripts/demo.py` against `{args.base_url}` on "
          f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
          "Every request below went through the public HTTP API.")
    t.add()

    ready = client.get("/ready").json()
    t.add("## 0. Service readiness (`GET /ready`)")
    t.code(ready)

    # ------------------------------------------------------------------ upload
    t.add("\n## 1. Upload (`POST /v1/documents`)")
    doc_ids = {}
    for path, tags, meta in SAMPLES:
        with path.open("rb") as fh:
            r = client.post(
                "/v1/documents",
                files={"file": (path.name, fh)},
                data={"tags": tags, "metadata": json.dumps(meta)},
            )
        body = r.json()
        if r.status_code >= 400:
            t.add(f"Upload of {path.name} failed: HTTP {r.status_code}")
            t.code(body)
            return 1
        doc = body["document"]
        doc_ids[path.name] = doc["id"]
        t.add(f"\n`{path.name}` -> **HTTP {r.status_code}** (duplicate={body['duplicate']})")
        t.code({k: doc[k] for k in ("id", "filename", "file_type", "language", "size_bytes", "status", "tags", "metadata")})

    # ------------------------------------------------------------------ poll
    t.add("\n## 2. Asynchronous processing (`GET /v1/documents/{id}` polled until `ready`)")
    started = time.time()
    final = {}
    while len(final) < len(doc_ids) and time.time() - started < 900:
        for name, did in doc_ids.items():
            if name in final:
                continue
            doc = client.get(f"/v1/documents/{did}").json()
            if doc["status"] in ("ready", "failed"):
                final[name] = (doc, round(time.time() - started, 1))
                print(f"  {name}: {doc['status']} after {final[name][1]}s")
        time.sleep(2)
    for name, (doc, secs) in final.items():
        t.add(f"\n`{name}` -> status **{doc['status']}** (observed after ~{secs}s)")
        t.code({k: doc[k] for k in ("id", "status", "chunk_count", "page_count", "embedding_model", "error", "processed_at")})
        if doc["status"] != "ready":
            return 1

    # ------------------------------------------------------------------ chunks
    t.add("\n## 3. Stored chunks (`GET /v1/documents/{id}/chunks`)")
    for name, did in doc_ids.items():
        chunks = client.get(f"/v1/documents/{did}/chunks", params={"limit": 200}).json()
        t.add(f"\n`{name}`: {chunks['total']} chunks")
        rows = ["| # | section | location | tokens | preview |", "|---|---|---|---|---|"]
        for ch in chunks["items"]:
            loc = (f"L{ch['start_line']}-{ch['end_line']}" if ch["start_line"]
                   else f"p.{ch['page_start']}-{ch['page_end']}")
            rows.append(f"| {ch['chunk_index']} | {ch['section'] or ''} | {loc} | {ch['token_count']} | "
                        f"{snippet(ch['content'], 80).replace('|', '/')} |")
        t.add("\n".join(rows))

    # ------------------------------------------------------------------ query
    t.add("\n## 4. Semantic search (`POST /v1/query`)")
    for q in QUERIES:
        payload = dict(q)
        if args.answer:
            payload["generate_answer"] = True
        r = client.post("/v1/query", json=payload)
        body = r.json()
        t.add(f"\n### Q: {q['query']}")
        if "filters" in q:
            t.add(f"Filters: `{json.dumps(q['filters'])}`")
        t.add(f"HTTP {r.status_code} - reranked={body.get('reranked')} hybrid={body.get('hybrid')} "
              f"- timings_ms={body.get('timings_ms')}")
        if not body.get("results"):
            t.add("\n_No results (as expected when filters exclude every matching document)._")
        for res in body.get("results", []):
            loc = (f"L{res['start_line']}-{res['end_line']}" if res["start_line"]
                   else f"page {res['page_start']}" + (f"-{res['page_end']}" if res["page_end"] != res["page_start"] else ""))
            sec = f" `{res['section']}`" if res["section"] and res["file_type"] == "code" else ""
            t.add(f"\n{res['rank']}. **{res['filename']}** {loc}{sec} - score {res['score']} "
                  f"(vector_rank={res['scores']['vector_rank']}, keyword_rank={res['scores']['keyword_rank']})")
            body_text = res["content"] if res["file_type"] == "code" else best_passage(res["content"], q["query"])
            t.add(f"   > {snippet(body_text, 420)}")
        if body.get("answer"):
            ans = body["answer"]
            t.add(f"\n**Generated answer** ({ans.get('model')}):" if ans.get("text") else f"\nAnswer error: {ans.get('error')}")
            if ans.get("text"):
                t.add("\n" + "\n".join("> " + line for line in ans["text"].splitlines()))

    # ------------------------------------------------------------------ dedupe
    t.add("\n## 5. Idempotent re-upload (content-hash de-duplication)")
    path, tags, meta = SAMPLES[1]
    with path.open("rb") as fh:
        r = client.post("/v1/documents", files={"file": (path.name, fh)})
    t.add(f"Re-uploading `{path.name}` -> HTTP {r.status_code}, duplicate={r.json()['duplicate']}, "
          f"same id: {r.json()['document']['id'] == doc_ids[path.name]}")

    # ------------------------------------------------------------------ validation
    t.add("\n## 6. Error handling")
    r = client.post("/v1/documents", files={"file": ("malware.exe", b"MZ\x90\x00")})
    t.add(f"\nUnsupported file type -> HTTP {r.status_code}")
    t.code({"error": {k: v for k, v in r.json()["error"].items() if k != "details"}})
    r = client.post("/v1/query", json={"query": "  ", "top_k": 500})
    t.add(f"\nInvalid query payload -> HTTP {r.status_code}")
    t.code(r.json())

    # ------------------------------------------------------------------ delete
    t.add("\n## 7. Delete (`DELETE /v1/documents/{id}`): soft delete, then purge")
    t.add("A throwaway markdown document is uploaded, found by search, deleted, and then no longer found.")
    md = b"# Runbook: rotating the staging database password\n\nThe staging DB password rotates every 30 days via the vault-rotator job.\n"
    r = client.post("/v1/documents", files={"file": ("staging_runbook.md", md)}, data={"tags": "runbook"})
    tmp_id = r.json()["document"]["id"]
    for _ in range(60):
        if client.get(f"/v1/documents/{tmp_id}").json()["status"] == "ready":
            break
        time.sleep(1)
    probe = {"query": "how often does the staging database password rotate", "top_k": 3}
    before = [x["filename"] for x in client.post("/v1/query", json=probe).json()["results"]]
    r = client.delete(f"/v1/documents/{tmp_id}")
    t.add(f"\nSearch before delete -> {before}")
    t.add(f"\n`DELETE /v1/documents/{tmp_id}` -> HTTP {r.status_code}")
    t.code(r.json())
    after = [x["filename"] for x in client.post("/v1/query", json=probe).json()["results"]]
    t.add(f"Search immediately after delete -> {after}")
    for _ in range(30):
        g = client.get(f"/v1/documents/{tmp_id}")
        if g.status_code == 404:
            break
        time.sleep(1)
    t.add(f"`GET /v1/documents/{tmp_id}` after background purge -> HTTP {g.status_code}")

    final_ready = client.get("/ready").json()
    t.add("\n## 8. Final state (`GET /ready`)")
    t.code(final_ready)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(t.lines) + "\n", encoding="utf-8")
    print(f"\nTranscript written to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
